### ISSUE TITLE
TransformError after start the app

### ISSUE THREAD

**Issue by oney** [Neson/RailsRelayReact3#1]
Got this
![2016-08-15 11 53 14](https://cloud.githubusercontent.com/assets/4091190/17671347/2f8932d0-6349-11e6-92f5-7cb516f76eed.png)
The issue should be related to https://github.com/facebook/react-native/issues/7814

**Comment by zetavg** [comment]
感謝 ❤️ ，已經用 rebase 修改了那顆 commit。

**Comment by oney** [comment]
👌
